apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: default
patches:
  - target:
    kind: Deployment
    name: nginx-deployment
  patch: |-
    apiVersion: apps/v1