---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgC3QYhKFwK38Ae2E3oU8UiUVncJ4nqMOW2plWHACeH7iATYW1dCdcSHQjRt7sHFqDISTSiJsxB9+oUZ13v54T8WF7mPUxd68hEMJpOGy6xaGMS8j/XpXm1UK5bNk5q7DD74CA4KC0WgNX1ovOyrFkFns5s14cXaPQ3TII8vCRfYz0OvER4iZgHb2hh8JxPX392jrThRe0wewljIQ5LCyjyCQx8uNkNBWxjvlKxGPawik27eSLtzDA8ozCBIgquh1FQxoMCTQGzrinvs4W9OB3StkAXf0J4x2KplLO+pNrvon/xsc25vVlEc+R3nbLAQ0L92zO9oYBV+YPWICXLYjgjrKNIquSX4ceTDGj8fSdDPsUNzevONA0yOA6KZo6v5qCCKjGi70TcPJYjUfgAB1UwOaoKurU1Jh+6hBq4dCYVVYHN0eeT/1pF/5DXuzeGGbKx6mDPIeGuBOpthMSscEgbPI2hPj8LCrvJnuSqF0lcp3u5yORp2MzSyYnD8feusTzSY7JKZoGWhvj4I4T3W7M+276bzHKIWKc8DOkG1Ed7ccWLAVy4lCfXrS48KAjpK3rWU+OC7DcwSniadz1B+5h9NVq57ofloLkTbPoBx9kpDipBSBpLKZcnEhOl+grbLcL2kvzcqEYh5Th01nMattCfKtSaqmhrmDCS/m7ZsRgctFBGJMRThQr79oI7iKo5ZwR8n608TR6nTCvxXHErumxS1uUo/tST+egP3loyvXwaKlimpJDVu3w==
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
