apiVersion: aronahl.k8s.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  project: default
  source:
    chart: httpbin 
    repoURL: "https://matheusfm.dev/charts"
    targetRevision: 0.1.1
    helm: 
      releaseName: httpbin
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
